name: class11
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- jupyterlab
- pandas
- geopandas
- descartes
- cartopy
- folium
- matplotlib
- seaborn
- streamlit
- spyder
- pip
- pip:
  - streamlit-folium
